server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: test
    password: test
    url: jdbc:postgresql://localhost:5432/test

  jpa:
    hibernate:
      ddl-auto: validate
      format_sql: true
      use_sql_comment: true
    show-sql: true
